[package]
name             = "libevdev-dev"
version          = "1.13.7"
description      = "libevdev headers, pkgconfig"
license          = "MIT"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://gitlab.freedesktop.org/libevdev/libevdev"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["libevdev"]
provides         = ["libevdev-dev"]
tags             = ["base", "input", "dev"]

[install]
include = "/overlayer/zexlib/union/include"
lib     = "/overlayer/zexlib/union/lib"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
