[package]
name             = "libevdev"
version          = "1.13.7"
description      = "Wrapper library for evdev devices"
license          = "MIT"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://gitlab.freedesktop.org/libevdev/libevdev"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = []
provides         = ["libevdev", "touchpad-edge-detector", "mouse-dpi-tool", "libevdev-tweak-device"]
tags             = ["base", "library", "input"]

[install]
lib     = "/overlayer/syshub/lib"
bin     = "/overlayer/syshub/bin"
_syshub = true

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
