[package]
name             = "ell"
version          = "0.83"
description      = "Embedded Linux Library"
license          = "LGPL-2.1-or-later"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://git.kernel.org/pub/scm/libs/ell/ell.git"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["musl"]
provides         = ["ell"]
tags             = ["base", "library"]

[install]
lib     = "/overlayer/syshub/lib"
_syshub = true

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
