[package]
name             = "gettext-dev"
version          = "1.0"
description      = "gettext headers"
license          = "LGPL-2.1-or-later"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://www.gnu.org/software/gettext/"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["gettext"]
provides         = ["gettext-dev"]
tags             = ["base", "dev"]

[install]
include = "/overlayer/zexlib/union/include"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
