[package]
name             = "gstreamer-dev"
version          = "1.28.8"
description      = "GStreamer headers and pkgconfig"
license          = "LGPL-2.1-or-later"
maintainer       = "Ali Zain <alizain@zainiumdynamics.tech>"
homepage         = "https://gstreamer.freedesktop.org"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["gstreamer", "glib-dev"]
provides         = ["gstreamer-dev"]
tags             = ["base", "multimedia", "library", "dev"]

[install]
include = "/overlayer/zexlib/union/include"
lib     = "/overlayer/zexlib/union/lib"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
