[package]
name             = "fontconfig-dev"
version          = "2.18.3"
description      = "fontconfig headers, pkgconfig"
license          = "MIT"
maintainer       = "Ali Zain <alizain@zainiumdynamics.tech>"
homepage         = "https://www.freedesktop.org/wiki/Software/fontconfig/"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["fontconfig"]
provides         = ["fontconfig-dev"]
tags             = ["base", "library", "fonts", "dev"]

[install]
include = "/overlayer/zexlib/union/include"
lib     = "/overlayer/zexlib/union/lib"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
