[package]
name             = "libtasn1"
version          = "4.21.0"
description      = "ASN.1 structure parser library"
license          = "LGPL-2.1-or-later"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://www.gnu.org/software/libtasn1/"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["musl"]
provides         = ["libtasn1"]
tags             = ["base", "library"]

[install]
bin     = "/overlayer/syshub/bin"
lib     = "/overlayer/syshub/lib"
_syshub = true

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
