[package]
name             = "openssl-dev"
version          = "4.0.1"
description      = "openssl headers, pkgconfig"
license          = "Apache-2.0"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://www.openssl.org/"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["openssl"]
provides         = ["openssl-dev"]
tags             = ["base", "crypto", "dev"]

[install]
include = "/overlayer/zexlib/union/include"
lib     = "/overlayer/zexlib/union/lib"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
