[package]
name             = "font-noto-arabic"
version          = "2026.10.01"
description      = "Noto Sans Arabic, Noto Naskh Arabic and Noto Nastaliq Urdu"
license          = "OFL-1.1"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://notofonts.github.io"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = []
provides         = ["font-noto-arabic"]
tags             = ["base", "fonts"]

[install]
share   = "/overlayer/syshub/share"
_syshub = true

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
