# manifest.toml — readline (syshub runtime tier)

[package]
name             = "readline"
version          = "8.3"
description      = "GNU Readline — runtime shared libraries libreadline/libhistory (musl/Zainium build)"
license          = "GPL-3.0-or-later"
maintainer       = "Ali Zain <alizain@zainiumdynamics.tech>"
homepage         = "https://tiswww.case.edu/php/chet/readline/rltop.html"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["ncurses"]
provides         = ["libreadline.so.8", "libhistory.so.8"]
tags             = ["terminal", "library"]

[install]
lib     = "/overlayer/syshub/lib"
_syshub = true

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
