[package]
name             = "libcap-dev"
version          = "2.78"
description      = "libcap headers, static lib, pkgconfig"
license          = "BSD-3-Clause OR GPL-2.0-only"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://sites.google.com/site/fullycapable/"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["libcap"]
provides         = ["libcap-dev"]
tags             = ["base", "dev"]

[install]
include = "/overlayer/zexlib/union/include"
lib     = "/overlayer/zexlib/union/lib"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
