[package]
name             = "libwebp-dev"
version          = "1.6.0"
description      = "libwebp headers, pkgconfig"
license          = "BSD-3-Clause"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://developers.google.com/speed/webp"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["libwebp"]
provides         = ["libwebp-dev"]
tags             = ["base", "library", "image", "dev"]

[install]
include = "/overlayer/zexlib/union/include"
lib     = "/overlayer/zexlib/union/lib"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []
