[package]
name             = "elfutils-dev"
version          = "0.195"
description      = "elfutils headers, static libs, pkgconfig"
license          = "GPL-2.0-or-later"
maintainer       = "Ali Zain <alizain@zainiumdynamics.tech>"
homepage         = "https://sourceware.org/elfutils/"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["elfutils"]
provides         = ["elfutils-dev"]
tags             = ["base", "library", "elf", "dev"]

[install]
include = "/overlayer/zexlib/union/include"
lib     = "/overlayer/zexlib/union/lib"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
