[package]
name             = "curl"
version          = "8.21.0"
description      = "URL retrieval utility and library"
license          = "curl"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://curl.se/"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["openssl", "zlib"]
provides         = ["curl", "libcurl"]
tags             = ["base", "network"]

[install]
lib     = "/overlayer/syshub/lib"
bin     = "/overlayer/syshub/bin"
_syshub = true

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
