# zlib-dev.manifest.toml — zlib (userland development tier)

[package]
name             = "zlib-dev"
version          = "1.3.2"
description      = "zlib compression — development headers, static library, pkgconfig"
license          = "Zlib"
maintainer       = "Ali Zain <alizain@zainiumdynamics.tech>"
homepage         = "https://zlib.net"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

requires_syshub  = ""
depends          = ["zlib"]
provides         = ["libz.a", "zlib.h"]
tags             = ["compression", "library", "development"]

[install]
lib     = "/overlayer/zexlib/union/lib"
include = "/overlayer/zexlib/union/include"
share   = "/overlayer/zexlib/union/share"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
