[package]
name             = "libarchive"
version          = "3.8.9"
description      = "Library that can create and read several streaming archive formats"
license          = "BSD-2-Clause AND BSD-3-Clause AND Public-Domain"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://libarchive.org/"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["zlib", "openssl"]
provides         = ["libarchive"]
tags             = ["base", "library", "archive"]

[install]
lib     = "/overlayer/syshub/lib"
bin     = "/overlayer/syshub/bin"
_syshub = true

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
